# Generated by Django 4.0.1 on 2022-02-03 23:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=50)),
                ('descendants', models.IntegerField(blank=True, null=True)),
                ('parent', models.IntegerField(blank=True, null=True)),
                ('ids', models.IntegerField(help_text="Item's unique Id", unique=True)),
                ('kids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('time', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('S', 'story'), ('J', 'job'), ('C', 'comment'), ('P', 'poll'), ('O', 'pollopt')], default='', max_length=1)),
                ('url', models.URLField()),
                ('deleted', models.BooleanField(default=False)),
                ('dead', models.BooleanField(default=False)),
                ('text', models.TextField(blank=True, max_length=500, verbose_name='text')),
                ('parts', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
            ],
            options={
                'ordering': ('-type',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hack.basemodel',),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hack.basemodel',),
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hack.basemodel',),
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hack.basemodel',),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hack.basemodel',),
        ),
    ]
