# Generated by Django 4.0.1 on 2022-02-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='by',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
