# Generated by Django 4.0.1 on 2022-02-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0002_alter_basemodel_by_alter_basemodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='type',
            field=models.CharField(choices=[('S', 'story'), ('J', 'job'), ('C', 'comment'), ('P', 'poll'), ('O', 'pollopt')], default='', max_length=10),
        ),
    ]
