# Generated by Django 4.0.1 on 2022-02-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0003_alter_basemodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='ids',
            field=models.IntegerField(help_text="Item's unique Id"),
        ),
    ]
