# Generated by Django 4.0.1 on 2022-02-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0005_alter_basemodel_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='by',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='dead',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='text',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='title',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
