# Generated by Django 4.0.1 on 2022-02-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0006_alter_basemodel_by_alter_basemodel_dead_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='PollOption',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
