# Generated by Django 4.0.1 on 2022-02-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0007_delete_comment_delete_job_delete_poll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='type',
            field=models.CharField(choices=[('S', 'story'), ('J', 'job'), ('C', 'comment'), ('P', 'poll'), ('O', 'pollopt')], max_length=10),
        ),
    ]
